version: '3.8'
services:
  tuitui-backend-green:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    ports:
      - "8444:8443"
    image: tuitui-backend-green
    # 컨테이너의 이름
    container_name: tuitui-backend-green
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    networks:
      - tuitui-api-network

networks:
  tuitui-api-network:
    driver: bridge